Repository Dreamvo/documentation, pull requests merged in 2018-06, with the labels that each got.

#8 Translating Introduction to english
  en/intro.md
Labels: Translation, good first issue

#9 Fix typo
  fr/intro.md
Labels: Grammar, enhancement

#11 Using new logo on documentation
  README.md
  en/intro.md
  fr/intro.md
  images/logo.png
  images/market_viewly.png
  images/tmp_logo.png
Labels: enhancement

#12 License english version
  README.md
  en/license.md
Labels: Translation, enhancement

#13 Moderation english version
  README.md
  en/moderation.md
Labels: Translation, enhancement
